// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-rZgONfxjCgQ52Bri4JV3C-8KKAgw0g',
    appId: '1:348302268612:web:c65105cff98a4c412c1191',
    messagingSenderId: '348302268612',
    projectId: 'travelapp-a839a',
    authDomain: 'travelapp-a839a.firebaseapp.com',
    storageBucket: 'travelapp-a839a.firebasestorage.app',
    measurementId: 'G-RJMXSZ30DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVvbAR4to4WRAq0RrrK6x66VBW-4TtXrQ',
    appId: '1:348302268612:android:2497b09eb353342c2c1191',
    messagingSenderId: '348302268612',
    projectId: 'travelapp-a839a',
    storageBucket: 'travelapp-a839a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbi2_sCu9LAu3uFfUAsireUBj_62OcxU',
    appId: '1:348302268612:ios:a25f9622516e8d6a2c1191',
    messagingSenderId: '348302268612',
    projectId: 'travelapp-a839a',
    storageBucket: 'travelapp-a839a.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQbi2_sCu9LAu3uFfUAsireUBj_62OcxU',
    appId: '1:348302268612:ios:a25f9622516e8d6a2c1191',
    messagingSenderId: '348302268612',
    projectId: 'travelapp-a839a',
    storageBucket: 'travelapp-a839a.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG-rZgONfxjCgQ52Bri4JV3C-8KKAgw0g',
    appId: '1:348302268612:web:8a1501960681dbdc2c1191',
    messagingSenderId: '348302268612',
    projectId: 'travelapp-a839a',
    authDomain: 'travelapp-a839a.firebaseapp.com',
    storageBucket: 'travelapp-a839a.firebasestorage.app',
    measurementId: 'G-GS5RHRVLRN',
  );
}
